# Site settings
title: Jason Green
email: jason@jasongreen.net
author: Jason Green
description: "An Exercise in Digital Identity."
baseurl: ""
url: "/"
google_analytics:
animated: true
show_related_posts: false

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
paginate_path: "blog/page:num"
sass:
  compressed: true
